// checksum 0x898f version 0x70013
/*
  This file was generated by the Qt Quick Application wizard of Qt Creator.
  QmlApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QMLAPPLICATIONVIEWER_H
#define QMLAPPLICATIONVIEWER_H

#include <QtDeclarative/QDeclarativeView>
#include <QWebPage>
#include <QtGui>
class MyWebPage : public QWebPage
{
    Q_OBJECT
public:
    MyWebPage():QWebPage()
      {
        connect(this,SIGNAL(linkClicked(QUrl)),this,SLOT(linkClicked(QUrl)),Qt::DirectConnection);

        connect(this,SIGNAL(unsupportedContent(QNetworkReply)),this,SLOT(linkClicked(QNetworkReply.url())),Qt::DirectConnection);
    };
protected:

    virtual QString userAgentForUrl(const QUrl &url) const
    {
        return QString::fromUtf8("Mozilla/5.0 (MeeGo; NokiaN9) AppleWebKit/534.13 (KHTML, like Gecko) NokiaBrowser/8.5.0 Mobile Safari/534.13");
        //return QString::fromUtf8("Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3 ");
    }
private slots:

  void linkClicked(QUrl url)
  {
   qDebug()<<"Hello! You Clicked: \n"+url.toString();
  };

};

class QmlApplicationViewer : public QDeclarativeView
{
    Q_OBJECT

public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };

    explicit QmlApplicationViewer(QWidget *parent = 0);
    virtual ~QmlApplicationViewer();

    static QmlApplicationViewer *create();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);

    // Note that this will only have an effect on Symbian and Fremantle.
    void setOrientation(ScreenOrientation orientation);

    void showExpanded();

private:
    class QmlApplicationViewerPrivate *d;
    MyWebPage *page;

};

QApplication *createApplication(int &argc, char **argv);

#endif // QMLAPPLICATIONVIEWER_H
